import { setItem } from './storage.js';

export function generateReport({ userProfile, chatSummary, triageTier, hospitalSelected }) {
  const report = {
    timestamp: Date.now(),
    userProfile: {
      name: userProfile.preferredName || 'Anonymous',
      age: userProfile.age,
      gender: userProfile.gender,
      height: userProfile.heightCm ? `${userProfile.heightCm} cm` : null,
      weight: userProfile.weightKg ? `${userProfile.weightKg} kg` : null,
    },
    chatSummary,
    triageTier,
    hospitalSelected: hospitalSelected || null,
  };

  setItem('hl_report', report);
  return report;
}

export function downloadReport(report) {
  const content = `
HEALTHBRIDGE — Patient Report
==============================
Date: ${new Date(report.timestamp).toLocaleString()}

PATIENT INFORMATION
Name: ${report.userProfile.name}
Age: ${report.userProfile.age || 'Not provided'}
Gender: ${report.userProfile.gender || 'Not provided'}
Height: ${report.userProfile.height || 'Not provided'}
Weight: ${report.userProfile.weight || 'Not provided'}

SYMPTOMS SUMMARY
${report.chatSummary}

TRIAGE LEVEL: ${report.triageTier?.toUpperCase()}

${report.hospitalSelected ? `SELECTED HOSPITAL
Name: ${report.hospitalSelected.name}
Phone: ${report.hospitalSelected.phone}
Address: ${report.hospitalSelected.address || 'N/A'}` : ''}
==============================
Generated by HealthBridge
  `.trim();

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `healthbridge-report-${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
