"""
memory.py
---------
Mem0 memory client setup and helper functions.
Handles storing and retrieving per-user memories across conversation sessions.
"""

from mem0 import MemoryClient, Memory
from config import (
    MEM0_API_KEY,
    USE_MEM0_CLOUD,
    MEMORY_TOP_K,
)


# ---------------------------------------------------------------------------
# Client Initialization
# ---------------------------------------------------------------------------

def _init_memory_client():
    """
    Initializes and returns the appropriate Mem0 client based on config.

    - Cloud mode:  Uses Mem0's hosted service (requires MEM0_API_KEY).
    - Local mode:  Runs Mem0 fully in-process with no external dependency.
    """
    if USE_MEM0_CLOUD:
        if not MEM0_API_KEY:
            raise RuntimeError(
                "MEM0_API_KEY must be set when USE_MEM0_CLOUD is True. "
                "Add it to your .env file."
            )
        return MemoryClient(api_key=MEM0_API_KEY)
    else:
        # Local Mem0 — no API key required, stores memories in-process
        return Memory()


# Singleton client — initialized once at module load time
memory_client = _init_memory_client()


# ---------------------------------------------------------------------------
# Helper Functions
# ---------------------------------------------------------------------------

def add_memory(user_id: str, user_message: str, bot_response: str) -> None:
    """
    Stores a conversation turn (user message + bot response) in Mem0.

    This builds long-term memory for the user so future conversations
    can reference past interactions.

    Args:
        user_id:      Unique identifier for the user.
        user_message: The message sent by the user.
        bot_response: The response generated by the chatbot.
    """
    messages = [
        {"role": "user",      "content": user_message},
        {"role": "assistant", "content": bot_response},
    ]
    memory_client.add(messages, user_id=user_id)


def get_relevant_memories(user_id: str, query: str) -> list[str]:
    """
    Retrieves the top-k most relevant past memories for a given user
    based on semantic similarity to the current query.

    Args:
        user_id: Unique identifier for the user.
        query:   The current user message, used as the search query.

    Returns:
        A list of memory strings (plain text), ready to be injected
        into the system prompt. Returns an empty list if none found.
    """
    try:
        results = memory_client.search(query, user_id=user_id, limit=MEMORY_TOP_K)

        # Mem0 returns a list of dicts with a "memory" key
        memories = [item["memory"] for item in results if "memory" in item]
        return memories

    except Exception as e:
        # Non-critical — gracefully degrade if memory retrieval fails
        print(f"[memory.py] Warning: Could not retrieve memories for user '{user_id}': {e}")
        return []


def format_memories_for_prompt(memories: list[str]) -> str:
    """
    Formats a list of memory strings into a numbered, readable block
    suitable for injection into the system prompt's {memories} slot.

    Args:
        memories: List of memory strings returned by get_relevant_memories().

    Returns:
        A formatted multi-line string, or an empty string if no memories.
    """
    if not memories:
        return ""
    return "\n".join(f"{i + 1}. {mem}" for i, mem in enumerate(memories))


def delete_user_memories(user_id: str) -> None:
    """
    Deletes ALL memories associated with a given user.
    Use with caution — this is irreversible.

    Args:
        user_id: Unique identifier for the user whose memories to delete.
    """
    memory_client.delete_all(user_id=user_id)
    print(f"[memory.py] All memories deleted for user '{user_id}'.")
